# Generated by Django 4.2.1 on 2023-06-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_alter_address_id_alter_agerating_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='userproduct',
            old_name='user_id',
            new_name='user',
        ),
    ]
