# Generated by Django 4.2.1 on 2023-06-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_alter_address_table_alter_agerating_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='age_rating_id',
            new_name='age_rating',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='userproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='userproduct',
            old_name='user_id',
            new_name='user',
        ),
    ]
