# Generated by Django 4.2.1 on 2023-06-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='address_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='image_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='role_id',
        ),
        migrations.RenameField(
            model_name='userproduct',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='userproduct',
            old_name='user',
            new_name='user_id',
        ),
    ]
