# Generated by Django 4.2.1 on 2023-06-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_rename_product_favorite_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='source',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../../static/images/'),
        ),
    ]
