# Generated by Django 4.2.1 on 2023-06-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_remove_image_source_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../../static/images/products'),
        ),
    ]
