# Generated by Django 4.2.1 on 2023-06-10 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0009_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='archives.product'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='archives.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='age_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='archives.agerating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='archives.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='archives.image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='archives.skill'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='archives.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='archives.image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='archives.role'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='archives.product'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='archives.user'),
        ),
    ]
