# Generated by Django 4.2.1 on 2023-06-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0010_alter_favorite_product_id_alter_favorite_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
    ]
